version: '3.7'
services:
  custom-autoscaler:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: custom-autoscaler:v1.0.0
    container_name: custom-autoscaler
    ports:
      - '4000:4000'
    restart: on-failure
    command: npm run docker
    logging:
      options:
        max-size: '50m'
        max-file: '5'
    volumes:
      - ./temp:/usr/src/app/temp
      - ./logs/indexer:/usr/src/app/logs
