---
apiVersion: v1
kind: Service
metadata:
  name: custom-autoscaler
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: custom-autoscaler
  namespace: autoscaler
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: custom-autoscaler
